In [2]:
import numpy as np

In [7]:
import collections as cols

In [8]:
import Tile as tl

In [28]:
from ast import literal_eval

In [49]:
import math

In [10]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,0]).reshape((3,3))

In [4]:
print(arr[0][1])

2


In [31]:
f = open("2solvable.txt", 'r')

In [33]:
f1 = f.readlines()

In [36]:
for line in f1:
    print(np.array(literal_eval(line)).reshape((3,3)))

[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 2 3]
 [4 0 5]
 [7 8 6]]
[[1 2 0]
 [4 5 3]
 [7 8 6]]


In [22]:
f.open()

In [34]:
print(f.closed)

True


AttributeError: '_io.TextIOWrapper' object has no attribute 'isOpen'

In [113]:
print(arr2)

[[ 2  0  4]
 [ 6 10  8]
 [12 14 16]]


In [83]:
S

NameError: name 'S' is not defined

In [18]:
1+3+3**2+3**3+3**4

121

In [111]:
hasSolution(arr)

True

In [71]:
def branchingFactor(nodes, depth):
    low = 0
    hi = nodes // 2
    counter = 0
    while low < hi and counter < 1000:
        counter +=1 
        guess = (hi + low) / 2
        factor = 0
        for d in range(depth+1):
            factor += (guess**d)
            
        if factor > nodes:
            hi = guess 
        else:
            low = guess
    return guess
    

In [74]:
branchingFactor(12,4)

1.4490336568196809

In [1]:
def branchingFactor2(nodes, depth):
    low = 0
    hi = nodes ** (1/depth)
    counter = 0
    while low < hi and counter < 1000:
        counter +=1 
        guess = (hi + low) / 2
        factor = 0
        for d in range(depth+1):
            factor += (guess**d / 1)
            
        if factor > nodes:
            hi = guess 
        else:
            low = guess
    return guess

In [2]:
branchingFactor2(1641,24)

1.2775434614391

In [3]:
f = 0
for x in range(25):
            f += (1.26**x / 1)
print(f)

1238.6363445221205


In [4]:
1641 - 1239

402